title: bockensm.com
description: Mark Bockenstedt's blog on ColdFusion, JavaScript, and other things web development related.
permalink: '/:year/:month/:day/:title'
baseurl: ""
url: "https://www.bockensm.com"
index: true

# Author Settings
author: Mark Bockenstedt
social-twitter: bockensm
social-github: bockensm

# Tracker
analytics: UA-159854083-1

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - github-pages
  - jekyll-gist

paginate: 10
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
